### ISSUE TITLE
Don’t have deathstaff in book 16, section 345

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#24]
After supposedly having grabbed the Deathstaff and going to the battle where it can be used (345), I don’t have it in my inventory. Maybe because I already had two normal weapons?

**Comment by cracrayol** [comment]
Deathstaff is a special item that can be used as a weapon, so having two weapons is not a problem.
And normally, there is a check that forbid going to the next section (270) if you don't have the deathstaff in your inventory.
Strange...

**Comment by lonevvolf** [comment]
I just played it through again, and the item is never added to the inventory. Granted, the book doesn’t seem to explicitly say to add it to the action chart, but then right after gives you the option to use it in battle. So the app doesn’t actually let you use that option.

**Comment by cracrayol** [comment]
Ok, there's two sections where picking the deathstaff is missing (225, 318). I'll fix it.
