### ISSUE TITLE
Book 17 start: drop Deathstaff?

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#28]
Although it’s not stated in the game, book 17 starts with the story that the death staff was lost after book 16, and it seems logical that Lone Wolf shouldn’t have it in special items anymore.

**Comment by cracrayol** [comment]
The death staff is dropped in the last section of book 16 (350). So, I don't see how you could have it at the start of book 17.

**Comment by lonevvolf** [comment]
Then there seems to be a bug there. I’ll check it later tonight.
