### ISSUE TITLE
New Order implementation?

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#30]
This is more of a discussion than an Issue, but do you have any problem or objection to starting implementation of the New Order books?  I know there is an Android app that implements them, but I really like the idea of a web-based app which works on all platforms and most likely has a longer life than a native mobile app.  Also nice to have everything implemented in one application from beginning to end.

I am very much interested in whether Holmgard Press will ever release a digital version, but I don't see that happening any time soon, and I hope that the Project Aon license will continue even in that case.

If you don't have anything against it, I would probably start implementing the books, since I am currently playing Book 18 through and should be running into New Order soon.  :)

**Comment by cracrayol** [comment]
I haven't implemented New Order because it's not fully available in project Aon (and will never be I think). But if you want to implement New Order, then go.

**Comment by lonevvolf** [comment]
Thanks for the info - I have made good progress on Book 21 so far.  Sections 1-100 are mostly done, and the main changed mechanics are implemented.  I still have to work on the new Kai Special Weapons implementation, and allowing the player to choose a custom Kai Name.  Once I have a first version, I will push it to my fork - let me know if you want me to create a branch or something to track these changes?

**Comment by lonevvolf** [comment]
Just created a PR for Book 21.  Would be very grateful for any feedback - I experimented with a few different implementations for some items, but settled on the simplest at the end, preferring not to add new mechanics if possible.
