### ISSUE TITLE
Missing tags through Book 20

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#31]
I've just finished Book 20, and throughout there are various checks for past experiences (tags) from past books.  While I have played through every book in order, two tags were missing:
torgar
vorndarol

The "torgar" tag is only assigned in sect346 of book 10.  According to the paths here:
https://www.[projectaon.org/en/svg/lw/10tdot.svgz](https://www.projectaon.org/en/svg/lw/10tdot.svgz)
it is possible to avoid sect346 by way of sect45.  I assume this is what happened here.

The "vorndarol" tag is only assigned in sect53 of book 16.  According to the paths here:
https://www.[projectaon.org/en/svg/lw/16tlov.svgz](https://www.projectaon.org/en/svg/lw/16tlov.svgz)
it is possible to avoid sect53 by way of sect220.

In the end, though, in this case it may make more sense to simply check in book 20 if the player has completed the relevant books, rather than having the tags.  It seems that the idea is to check their general story experiences rather than having encountered a specific event.

**Comment by cracrayol** [comment]
I've changed the location of torgar and vorndarol tags in books 10/16.
