### ISSUE TITLE
downloaddata fails with @types/selenium-webdriver error

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#32]
Something got corrupted in the last commit - looks like package-lock.json was changed but the change isn't complete?
When running:
`npm run downloaddata`

I get:

```
node_modules/@types/selenium-webdriver/chromium.d.ts:1:8 - error TS1192: Module '"C:/Users/Ryan Adler/repos/kaichronicles/node_modules/@types/selenium-webdriver/http"' has no default export.

1 import http from "./http";
         ~~~~

node_modules/@types/selenium-webdriver/lib/webdriver.d.ts:15:8 - error TS1192: Module '"C:/Users/Ryan Adler/repos/kaichroniclesnicles/node_modules/@types/selenium-webdriver/lib/command"' has no default export.

15 import command, { Command } from "./command";
          ~~~~~~~
```

**Comment by cracrayol** [comment]
No error on my side. I've just made "npm update" to upgrade packages.

Perhaps your version of node and/or npm is too old ? Mine is node v22.10/npm v10.7

**Comment by cracrayol** [comment]
Ok, the problem was in the latest version (4.1.23) of @types/selenium-webdriver. I've force the version to 4.1.22. Should be ok now.
