### ISSUE TITLE
CombatSkillModifier no default value

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#34]
I'm not sure if this is intentional, or an issue.

The default combatSkillModifier for combats is not set.  This means that if any item is added with a combatSkillModifierIncrement, each time that page is reloaded (ie. user goes to Action Chart and back to the section), the increment is reapplied.  Setting the combatSkillModifier to 0 on the base combat item resolves this, but it opens up a chance for a mistake when authoring the books.

**Comment by cracrayol** [comment]
It's a bug.
I've fixed it by forcing combatSkillModifier to be 0 if not defined.
