### ISSUE TITLE
Multi-currency Implementation

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#40]
@cracrayol Book 23 has heavy use of multiple currencies, so I would like to implement a proper handling.  This means basically invalidating the beltPouch variable in the actionChart - what have you done in the past regarding loading of old save files?

**Comment by cracrayol** [comment]
I've never (I think) changed the structure of the save file, only added contents.

**Comment by lonevvolf** [comment]
I see this is done in ActionChart.fromObject to upgrade old saves to newer.  I will extend this when updating to multicurrency Belt Pouch (and will create PR against this issue when done)
