### ISSUE TITLE
Kai Chronicles available on Project Aon website

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#53]
@cracrayol  This is not really an issue, but I wanted to update you that I've been able to get permission to publish Kai Chronicles to the Project Aon website.  I have a branch in my repository which publishes there once updates are pushed. 
The website is available at https://kaichronicles.projectaon.org

If you would like to create a new post in the forums there, it would be nice to let people know that we've added new books, and that the app is officially available there.  Since you are still the owner of the main repo, I think it's best to have the post from you like the previous posts.

**Comment by cracrayol** [comment]
Ok. I'm going to post it on the board of PA.
