### ISSUE TITLE
Fireseeds not stacking

### ISSUE THREAD

**Issue by lonevvolf** [cracrayol/kaichronicles#8]
If I have 2 fireseeds from the previous book, and take one at the outset of a book, it doesn't get added to the same "stack".  They total two items (stack of 2, stack of 1)

**Comment by cracrayol** [comment]
Need some dev, the stacking of fireseed is not implemented.

For reference :
[Q:] In some books you can choose Fireseeds at the start. It says 3 Fireseeds--if you take all three does this mean you have taken 3 [separate] items from the 5 you are allowed to pick? . . .

[A:] The Fireseeds are Special Items which count only as 1 item no matter how many of them you possess. However, when you use them be sure to note how many you have left. Also, for the purpose of determining your maximum number of Special Items (12), all Fireseeds count as 1 item.

**Comment by lonevvolf** [comment]
I may try to tackle this later on

**Comment by lonevvolf** [comment]
@cracrayol Assuming they stack, when taking fireseeds from the beginning of book 9, should the player automatically take all three, or should they have the option to take single ones?  I'm looking at implementing this, but not sure about the mechanics.  Basically they can work similar to arrows or meals (adding to a count of existing items) - with arrows, it automatically takes as many as possible to fill the quiver, so I'm thinking when taking the item, it can just add 3 to the count.

**Comment by cracrayol** [comment]
I've merged your code but made some changes to fix some problems.

**Comment by lonevvolf** [comment]
Great!  I was hesitant to add the count attribute to the `<drop>` tags, but I didn't want to presume to change the default workings of the functions.  I like your solution better, thanks!
